server:
  port: 0
spring:
  application:
    name: user-service
#  zipkin: # 서비스간 통신 추적
#    base-url: http://127.0.0.1:9411
#    enabled: true
  rabbitmq:
#    host: 127.0.0.1 #로컬
    host: rabbitmq
    port: 5672  #moqp프로토콜
    username: guest
    password: guest
  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
        hibernate:
          show_sql: true # 띄어 쓰기 8칸
          format_sql: true # Pretty Query
          use_sql: true
          use_sql_comments: true # JPQL 주석 형태로 쿼리가 나온다.확인 용도
          default_batch_fetch_size: 100 # TODO: 500 # 최초 사용 시점에 100개 미리 로딩
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url :
#      defaultZone : http://localhost:8761/eureka  # 로컬
      defaultZone: http://discovery-service:8761/eureka  # 도커 같은 네트워크
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


service:
   check: welcome user-service

# feign 클라이트 로그
logging:
  level:
    com.example.userservice.client: DEBUG

## 스프링 acutorat 사용시
management:
  endpoints:
    web:
      exposure:
        include: refresh ,httptrace, health , beans ,busrefresh ,  info, metrics, prometheus



