server:
  port: 0
spring:
  application:
    name: catalog-service
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/catalog
    url: jdbc:mariadb://mariadb:3306/catalog

    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url :
      defaultZone : http://discovery-service:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




